name: test promote env

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: npm install, build, and test
              run: |
                echo "build"
    deployDev:
        name: Deploy to Dev
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Development"
        steps:
            - name: Deploy to Dev
              run: |
                echo "Deploy DEV"
    deployProd:
        name: Deploy to PROD
        runs-on: ubuntu-latest
        needs: deployDev
        environment:
            name: "Production"
        steps:
            - name: Deploy to PROD
              run: |
                echo "Deploy PROD"